---
- hosts: imagersite
  remote_user: ubuntu
  environment:
    SECRET_KEY: "{{ SECRET_KEY }}"
    DB_NAME: "{{ DB_NAME }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    ALLOWED_HOSTS: "{{ ALLOWED_HOSTS }}"
    DJANGO_SETTINGS_MODULE: "{{ DJANGO_SETTINGS_MODULE }}"
    EMAIL_HOST: "{{ EMAIL_HOST }}"
    EMAIL_PORT: "{{ EMAIL_PORT }}"
    EMAIL_HOST_USER: "{{ EMAIL_HOST_USER }}"
    EMAIL_HOST_PASSWORD: "{{ EMAIL_HOST_PASSWORD }}"
    EMAIL_USE_TLS: "{{ EMAIL_USE_TLS }}"
    EMAIL_TIMEOUT: "{{ EMAIL_TIMEOUT }}"
    DEFAULT_FROM_EMAIL: "{{ DEFAULT_FROM_EMAIL }}"

  tasks:
    - name: Update the base Unbutu image
      apt: update_cache=yes
      become: yes
      become_method: sudo

    - name: Install build dependencies
      apt: name={{ item }} state=latest update_cache=yes
      become: yes
      become_method: sudo
      with_items:
        - python-dev
        - python3-venv
        - python3-pip
        - build-essential
        - postgresql-client
        - nginx

    - name: Clone project
      git:
        repo: https://github.com/keitheck/django-imager.git
        dest: /home/ubuntu/django-imager
        version: master

    - name: Install project requirements
      command: pip install -r django-imager/requirements.txt
      become: yes
      become_method: sudo

    - name: Collect static
      command: python3 django-imager/imagersite/manage.py collectstatic --noinput

    - name: Install Gunicorn into Virtual Environment
      pip: name=gunicorn
      become: yes
      become_method: sudo

    - name: Register the backup default config for nginx
      stat: path=/etc/nginx/sites-available/default.bak
      register: default_stat

    - name: mv and rename default nginx config
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
      become: yes
      become_method: sudo
      when: not default_stat.stat.exists

    - name: Create a new Nginx config
      template:
        src: templates/nginx_config
        dest: /etc/nginx/sites-available/default
      become: yes
      become_method: sudo

    - name: Create a new gunicorn config
      template:
        src: templates/gunicorn.service
        dest: /etc/systemd/system/gunicorn.service
      become: yes
      become_method: sudo
    
    - name: Check status of gunicorn
      command: systemctl status gunicorn
      register: service_gunicorn_status

      #- name: Restart gunicorn if started
      #command: systemctl restart gunicorn
      #become: yes
      #become_method: sudo
      #when: service_gunicorn_status | active
      
    - name: Start gunicorn
      command: systemctl start gunicorn.service
      become: yes
      become_method: sudo
      #when: service_gunicorn_status | inactive

    - name: Check status of nginx
      command: systemctl status nginx
      register: service_nginx_status

      #- name: Restart nginx if started
      #command: systemctl restart nginx
      #become: yes
      #become_method: sudo
      #when: service_nginx_status | active

    - name: Start nginx
      command: systemctl start nginx
      become: yes
      become_method: sudo
      #when: service_nginx_status | inactive

    - name: Migrate database files
      command: python3 django-imager/imagersite/manage.py migrate
